version: "3"

networks:
  internal:
    driver: bridge

services:
  handyman:
    build:
      context: ../handyman/
    networks:
      - internal
    ports:
      - "8080:8080"
      - "9090:9090"
    restart: always
    environment:
      - grpc.server.address=0.0.0.0
      - DB_USERNAME=postgres
      - DB_PASSWORD=123
      - DB_URL=jdbc:postgresql://postgres:5432/postgres?currentSchema=public
    container_name: handyman
    image: handyman:0.2.1
    depends_on:
      - postgres
  landscape:
    build:
      context: ../landscape/
    networks:
      - internal
    ports:
      - "8081:8081"
    environment:
      - grpc.client.HandymanService.address=static://handyman:9090
      - grpc.client.RancherService.address=static://rancher:9092
      - DB_USERNAME=postgres
      - DB_PASSWORD=123
      - DB_URL=jdbc:postgresql://postgres:5432/postgres?currentSchema=public
    restart: always
    container_name: landscape
    image: landscape:0.2.1
    depends_on:
      - handyman
      - rancher
      - postgres
  rancher:
    build:
      context: ../rancher/
    networks:
      - internal
    ports:
      - "8082:8082"
      - "9092:9092"
    restart: always
    environment:
      - grpc.server.address=0.0.0.0
      - DB_USERNAME=postgres
      - DB_PASSWORD=123
      - DB_URL=jdbc:postgresql://postgres:5432/postgres?currentSchema=public
    container_name: rancher
    image: rancher:0.2.1
    depends_on:
      - postgres
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9096:9090"
    networks:
      - internal
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "9095:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - internal
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres
    networks:
      - internal

volumes:
  postgres-data:
