apiVersion: apps/v1
kind: Deployment
metadata:
  name: handyman
spec:
  selector:
    matchLabels:
      app: handyman
  replicas: 2
  template:
    metadata:
      labels:
        app: handyman
    spec:
      containers:
        - name: handyman
          image: handyman:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
            - containerPort: 9090
          env:
            - name: grpc.server.address
              value: 0.0.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: handyman
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: handyman-http
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: handyman-grpc
  type: NodePort
  selector:
    app: handyman