apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher
spec:
  selector:
    matchLabels:
      app: rancher
  replicas: 2
  template:
    metadata:
      labels:
        app: rancher
    spec:
      containers:
        - name: rancher
          image: victorminsky/rancher:0.2.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
            - containerPort: 9092
          env:
            - name: grpc.server.address
              value: 0.0.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: rancher
spec:
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      name: handyman-http
    - protocol: TCP
      port: 9092
      targetPort: 9092
      name: handyman-grpc
  type: NodePort
  selector:
    app: rancher